spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
  h2:
    console:
      enabled: true
jwt:
  secret: ENC(gzh7qZkZbkoOqVVeliYNMNuabmFSyP4S5N5tiCAw6w+V8F2LF6vTGEWV7zH5hKkBIOBQalsk9roPp7WVLcyVwq6m2nxEJykbkDS+ZgCzXR/5knBfKemBtw==)
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : ${JASYPT_PASSWORD}
