spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql:doranteacher-springboot-webservice.c8dbmoyeyryd.ap-northeast-2.rds.amazonaws.com:3306:doranteacher
      username: doran
      password: ehfksToa2022!
      driver-class-name: com.mysql.cj.jdbc.Driver
